name: Deploy

on:
  push:
    branches: [ master ]

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.77.0'
        extended: true

    - name: Build
      run: hugo --minify

    - name: List output files
      run: ls public/

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0   # FTPを使ってサーバーにDeployするアクションを実行
      env:                                        
        FTP_SERVER: ${{ secrets.FTP_SERVER }}     # FTPサーバーのURLを設定
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }} # FTPのユーザー名を設定
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} # FTPのパスワードを設定
        LOCAL_DIR: public                           # どのディレクトリのデータをアップロードするか
        REMOTE_DIR: /obenkyonokai.com      # ロリポップ！FTPサーバのどのディレクトリにアップロードするか
        ARGS: --delete
