name: Deploy

on:
  push:
    branches: [ master ]

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.101.0' #hugoのバージョンを記述
        extended: true

    - name: Build
      run: hugo --minify

    - name: List output files
      run: ls public/

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0   # FTPを使ってサーバーにDeployするアクションを実行
      with:                                        
        server: ${{ secrets.FTP_SERVER }}     # FTPサーバーのURLを設定
        username: ${{ secrets.FTP_USERNAME }} # FTPのユーザー名を設定
        password: ${{ secrets.FTP_PASSWORD }} # FTPのパスワードを設定
        local-dir: public                           # どのディレクトリのデータをアップロードするか
        server-dir: /obenkyonokai.com      # ロリポップ！FTPサーバのどのディレクトリにアップロードするか

